### ISSUE TITLE
Add option for creating a third-body species in the MICM configuration

### ISSUE THREAD

**Issue by mattldawson** [NCAR/musica#115]
Allow users to specify that a species should be treated as a "third-body" species whose concentration is automatically set to the total air density (mol m-3).

**Acceptance Criteria**
- A MICM configuration can include a species whose concentration is always equal to the total air density (mol m-3)

**Ideas**
- Add a new tracer type option for third-body species:
```
{
  "name": "M",
  "type": "CHEM_SPEC",
  "tracer type": "THIRD_BODY"
}
```
- Have the configuration parser use the `micm::Species::ThirdBody()` function to create a species flagged with `THIRD_BODY`

**Comment by boulderdaze** [comment]
Completed
