### ISSUE TITLE
Update MICM wrapper to use SolverBuilder

### ISSUE THREAD

**Issue by mattldawson** [NCAR/musica#146]
Update the MICM wrapper code to use the new `SolverBuilder` class to create instances of the Rosenbrock solver.

**Acceptance Criteria**
- MUSICA tests pass when linking against the latest commit on main in the MICM repo

**Ideas**
- Update the creation of the Rosenbrock solver here:
  https://github.com/NCAR/musica/blob/d09c3befe111c8a2de1aefbc4d43c40f5122f690/src/micm/micm.cpp#L171-L179

to use the same logic as in the MICM tests:
https://github.com/NCAR/micm/blob/f8f46dfac286cd5e2227537d04ff9c48c08a0ae9/test/unit/solver/test_solver_builder.cpp#L90-L95

**Comment by K20shores** [comment]
Fixed by #140
