### ISSUE TITLE
Create an action to publish to pypi when we make a release

### ISSUE THREAD

**Issue by mattldawson** [NCAR/musica#159]
Add an action that publishes the MUSICA Python wrapper to pypi for each release.

**Acceptance Criteria**
- The MUSICA Python package is deployed to pypi on each commit to the release branch

**Ideas**
- Follow the logic [here](https://github.com/pybind/cmake_example/blob/master/.github/workflows/wheels.yml) and [here](https://github.com/pybind/cmake_example/blob/7a94877f581a14de4de1a096fb053a55fc2a66bf/pyproject.toml#L33-L38)
- Apparently, can set up [publishers](https://docs.pypi.org/trusted-publishers/) with pypi so that we don't need to store a token
- Investigate whether it's possible to have the version number in just one place, instead of in both the CMakeLists.txt file and pyproject.toml

**Comment by WardF** [comment]
This was part of the discussion we had had @K20shores if I'm not mistaken, should I take this on as well?

**Comment by K20shores** [comment]
@WardF yes, but also I ended up workin on this last week and #184, I think, accomplishes this
