### ISSUE TITLE
Remove fetch content integration

### ISSUE THREAD

**Issue by boulderdaze** [NCAR/musica#185]
The purpose of the fetch content is to support cross-compiling but `musica` doesn't have that requirement anymore

**Ideas**
- Move integration tests in `fortran/test/fetch_content_integration/` to `fortran/test/integration/`
- Remove `fortran/test/fetch_content_integration/CMakeLists.txt`
- Remove the fetch content integration tests from the CI workflows

**Comment by mattldawson** [comment]
I think we still need to support cross-compiling - it's the only way the JIT-compiled code (and maybe the CUDA code also?) can be used with a fortran wrapper compiled with intel compilers

**Comment by boulderdaze** [comment]
I haven't thought about JIT-compiled code. Do you agree @K20shores? If we all are on the same page, I will delete the issue.

**Comment by K20shores** [comment]
@mattldawson @boulderdaze Could we just rework the tests so that we test cross compiling directly? I just think testing fetch content makes it hard to correctly test the current branch and we don't need to be testing if cmake's stuff works

**Comment by boulderdaze** [comment]
Yeah, I agree it makes hard to test the current branch. I think we can remove the fetch content part from the current test setup and keep the cross compiling test

**Comment by boulderdaze** [comment]
We think using fetch content is simpler to support cross compiling test. Closing the issue.
