### ISSUE TITLE
Incorrect rate constant ordering

### ISSUE THREAD

**Issue by K20shores** [NCAR/musica#203]
I simply added an extra cell to the receiving array (line 721 of music_box.py):
        ordered_rate_constants = (len(rate_constants.keys()) + 1) * [0.0]   # bogus + 1

**Acceptance criteria**

**Ideas**
- Add TS1 as a test of the python interface to see the issue and make sure it doesn't come up again

**Comment by carl-drews** [comment]
Carl Drews
  Tuesday at 4:18 PM [August 13, 2024]
musica is giving me a gap in the rate_constant_ordering on line 477 of music_box.by:
        rate_constant_ordering = musica.user_defined_reaction_rates(
            self.solver)
INFO:acom_music_box.music_box:key = PHOTO.jterpooh   value = 0   ordering = 92 92
INFO:acom_music_box.music_box:key = PHOTO.jcl2   value = 0   ordering = 93 93
INFO:acom_music_box.music_box:key = PHOTO.**jch3cho**   value = 0   ordering = **95** 94
INFO:acom_music_box.music_box:key = PHOTO.jbigald1   value = 0   ordering = 96 95
INFO:acom_music_box.music_box:key = PHOTO.jhno3   value = 0   ordering = 97 96

**Comment by K20shores** [comment]
This may actually be a bug in music-box. It looks like parsing the initial conditions file for rate constants is only matching on the name after something like `PHOT.NO2`. But, if you have `PHOT.NO2` and `EMIS.NO2`, only one of these would be recognized

**Comment by mattldawson** [comment]
closing since it looks like it's in MusicBox. can reopen if necessary
