### ISSUE TITLE
Add MICM, TUV-x to CAM-SIMA

### ISSUE THREAD

**Issue by K20shores** [NCAR/musica#40]
#  Nice to have, not required

- [ ] #18
- [ ] #54
- [x] #94

#  Documentation

- [x] #63 
- [ ] #69

#  General
- [ ] #108

# MICM

- [x] #33
- [x] #48
- [x] #38
- [x] #134
- [x] #103
- [ ] #58
- [ ] #55
- [ ] #123
- [x] #66
- [ ] #83
- [x] #115
- [ ] #117
- [ ] #60

 # TUV-x
- [x] #29
- [x] #90
- [x] #46
- [ ] #120 
- [ ] #121 
- [ ] #122
- [ ] #43
- [ ] #123
- [ ] #118
- [ ] #119
- [ ] #120
- [ ] #121
- [ ] #122
- [ ] https://github.com/NCAR/tuv-x/issues/87
- [ ] https://github.com/NCAR/musica/issues/138

**Comment by mattldawson** [comment]
will track these issues using the MICM, TUV-x in CAM-SIMA milestone
