### ISSUE TITLE
Create documentation for MUSICA

### ISSUE THREAD

**Issue by mattldawson** [NCAR/musica#63]
Create a roughed-in documentation for MUSICA following the approach used in MICM [here](https://github.com/NCAR/micm/tree/main/docs).

**Acceptance Criteria**
- Automated documentation built and hosted somewhere

**Ideas**
- Create a Sphinx configuration
- Add a GH Action for building docs on new commits to main and release
- Save a version of the documentation for each tagged release that allows users to view documentation for previous versions
- Publish docs to GitHub Pages

**Comment by K20shores** [comment]
Related, #58

**Comment by mattldawson** [comment]
completed with #95
